### ISSUE TITLE
(Pythonista 2.0) requests SSL failing

### ISSUE THREAD

**Issue by wizardofozzie** [ywangd/pythonista-tools-installer#5]
```
>>> import requests as r; o=open('ptinstaller.py','w'); o.write(r.get('http://j.mp/pt-i').text); o.close()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/var/mobile/Containers/Bundle/Application/BEB7C0AA-4CC7-464D-9A76-DBEC758FECB7/Pythonista.app/Frameworks/PythonistaKit.framework/pylib/site-packages/requests/api.py", line 65, in get
    return request('get', url, **kwargs)
  File "/var/mobile/Containers/Bundle/Application/BEB7C0AA-4CC7-464D-9A76-DBEC758FECB7/Pythonista.app/Frameworks/PythonistaKit.framework/pylib/site-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/var/mobile/Containers/Bundle/Application/BEB7C0AA-4CC7-464D-9A76-DBEC758FECB7/Pythonista.app/Frameworks/PythonistaKit.framework/pylib/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/mobile/Containers/Bundle/Application/BEB7C0AA-4CC7-464D-9A76-DBEC758FECB7/Pythonista.app/Frameworks/PythonistaKit.framework/pylib/site-packages/requests/sessions.py", line 599, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/var/mobile/Containers/Bundle/Application/BEB7C0AA-4CC7-464D-9A76-DBEC758FECB7/Pythonista.app/Frameworks/PythonistaKit.framework/pylib/site-packages/requests/sessions.py", line 192, in resolve_redirects
    allow_redirects=False,
  File "/var/mobile/Containers/Bundle/Application/BEB7C0AA-4CC7-464D-9A76-DBEC758FECB7/Pythonista.app/Frameworks/PythonistaKit.framework/pylib/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/var/mobile/Containers/Bundle/Application/BEB7C0AA-4CC7-464D-9A76-DBEC758FECB7/Pythonista.app/Frameworks/PythonistaKit.framework/pylib/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:504: error:140773E8:SSL routines:SSL23_GET_SERVER_HELLO:reason(1000)

```

**Comment by ywangd** [comment]
It works for me. Maybe check whether you have internet access? Also try restart Pythonista completely (i.e. double click home and swipe up to remove Pythonista from task list).

**Comment by wizardofozzie** [comment]
I've tried both of those suggestions.
The only thing that worked was a reinstall, but then restoring my old files raised the same bug

**Comment by ywangd** [comment]
That's weird. Maybe use `urllib` instead of `requests`? Try following one line

``` Python
import urllib2; o=open('ptinstaller.py','w'); o.write(urllib2.urlopen('http://j.mp/pt-i').read()); o.close()
```

**Comment by Aareon** [comment]
Works consistently okay in my experience. This issue is also super old. Can be closed.
